services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: datahub
      POSTGRES_PASSWORD: datahub
      POSTGRES_DB: datahub
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "datahub"]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"
    restart: always

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: datahub
    volumes:
      - ${MONGO_VOLUME}:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - "27017:27017"
    restart: always