"""Integrations Tables

Revision ID: 13013f99c854
Revises: 41c1d0812a62
Create Date: 2026-03-09 01:06:35.129804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13013f99c854'
down_revision: Union[str, Sequence[str], None] = '41c1d0812a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS hub")
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type_api', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=100), nullable=False),
    sa.Column('timeout', sa.Time(), nullable=False),
    sa.Column('generic_fetcher', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hub'
    )
    op.create_index(op.f('ix_hub_integrations_id'), 'integrations', ['id'], unique=False, schema='hub')
    op.create_index(op.f('ix_hub_integrations_name'), 'integrations', ['name'], unique=False, schema='hub')
    op.create_table('auth_providers',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('auth_endpoint', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('mutation', sa.String(length=255), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('response_type', sa.String(length=50), nullable=False),
    sa.Column('token_field', sa.String(length=255), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['hub.integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hub'
    )
    op.create_index(op.f('ix_hub_auth_providers_id'), 'auth_providers', ['id'], unique=False, schema='hub')
    op.create_table('request_details',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('request_type', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['hub.integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hub'
    )
    op.create_index(op.f('ix_hub_request_details_id'), 'request_details', ['id'], unique=False, schema='hub')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hub_request_details_id'), table_name='request_details', schema='hub')
    op.drop_table('request_details', schema='hub')
    op.drop_index(op.f('ix_hub_auth_providers_id'), table_name='auth_providers', schema='hub')
    op.drop_table('auth_providers', schema='hub')
    op.drop_index(op.f('ix_hub_integrations_name'), table_name='integrations', schema='hub')
    op.drop_index(op.f('ix_hub_integrations_id'), table_name='integrations', schema='hub')
    op.drop_table('integrations', schema='hub')
    # ### end Alembic commands ###
