"""integration_logs_table

Revision ID: 9e520d4541b5
Revises: c3327b64a720
Create Date: 2026-03-11 05:55:45.248069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e520d4541b5'
down_revision: Union[str, Sequence[str], None] = 'c3327b64a720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador do log'),
    sa.Column('log_uuid', sa.UUID(), nullable=True, comment='UUID do Log'),
    sa.Column('origin_system', sa.String(), nullable=True, comment='Sistema de origem: Fidelize Funcional / Interplayers'),
    sa.Column('component_name', sa.String(), nullable=True, comment='fetcher, parser,observer'),
    sa.Column('process_name', sa.String(), nullable=True, comment='Classe que está executando o processo'),
    sa.Column('message_text', sa.String(), nullable=True, comment='Mensagem do log'),
    sa.Column('file_path', sa.String(), nullable=True, comment='Caminho do arquivo no bucket para TXT'),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON com pré-pedidos'),
    sa.Column('file_type', sa.String(), nullable=True, comment='Tipo do arquivo: txt / json'),
    sa.Column('error_details', sa.String(), nullable=True, comment='Descrição do erro'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='Data de criação do log'),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True, comment='Data de início do processamento'),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True, comment='Data de término do processamento'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Duração do processamento em milissegundos'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, comment='Data da última atualização do log'),
    sa.Column('status', sa.String(), nullable=True, comment='Status do processamento: SUCCESS, FAILED, STARTED, IN_PROGRESS'),
    sa.PrimaryKeyConstraint('id'),
    schema='logs'
    )
    op.create_index('log_idx_uuid', 'integration_logs', ['log_uuid'], unique=False, schema='logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('log_idx_uuid', table_name='integration_logs', schema='logs')
    op.drop_table('integration_logs', schema='logs')
    # ### end Alembic commands ###
