"""PrePedidoLogs table

Revision ID: c3327b64a720
Revises: 13013f99c854
Create Date: 2026-03-11 04:53:40.567780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c3327b64a720'
down_revision: Union[str, Sequence[str], None] = '13013f99c854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Altera o tipo do campo timeout de Time para Integer (mudança feita no model Integrations)
    op.alter_column('integrations', 'timeout',
        existing_type=sa.Time(),
        type_=sa.Integer(),
        nullable=False,
        schema='hub',
        postgresql_using="EXTRACT(EPOCH FROM timeout)::integer"
    )

    # Cria o schema logs e a nova tabela log_pre_pedidos_vans
    op.execute("CREATE SCHEMA IF NOT EXISTS logs")
    op.create_table('log_pre_pedidos_vans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_van_id', sa.String(length=255), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('log_uuid', sa.UUID(), nullable=True),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('integration_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['hub.integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='logs'
    )
    op.create_index(op.f('ix_logs_log_pre_pedidos_vans_id'), 'log_pre_pedidos_vans', ['id'], unique=False, schema='logs')
    op.create_index(op.f('ix_logs_log_pre_pedidos_vans_log_uuid'), 'log_pre_pedidos_vans', ['log_uuid'], unique=False, schema='logs')
    op.create_index(op.f('ix_logs_log_pre_pedidos_vans_message_id'), 'log_pre_pedidos_vans', ['message_id'], unique=False, schema='logs')
    op.create_index(op.f('ix_logs_log_pre_pedidos_vans_pedido_van_id'), 'log_pre_pedidos_vans', ['pedido_van_id'], unique=False, schema='logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_log_pre_pedidos_vans_pedido_van_id'), table_name='log_pre_pedidos_vans', schema='logs')
    op.drop_index(op.f('ix_logs_log_pre_pedidos_vans_message_id'), table_name='log_pre_pedidos_vans', schema='logs')
    op.drop_index(op.f('ix_logs_log_pre_pedidos_vans_log_uuid'), table_name='log_pre_pedidos_vans', schema='logs')
    op.drop_index(op.f('ix_logs_log_pre_pedidos_vans_id'), table_name='log_pre_pedidos_vans', schema='logs')
    op.drop_table('log_pre_pedidos_vans', schema='logs')

    # Reverte o campo timeout de Integer para Time
    op.alter_column('integrations', 'timeout',
        existing_type=sa.Integer(),
        type_=sa.Time(),
        nullable=False,
        schema='hub'
    )
    # ### end Alembic commands ###
