from sqlalchemy import (
    Column, Integer, String, Float, Date, DateTime, ForeignKey, BigInteger, TIMESTAMP, func,
)
from sqlalchemy.orm import relationship

from app.infrastructure.db.models.default_datahub.default_table import DefaultAttributesModel
from app.infrastructure.db import Base


class NotaFiscal(Base, DefaultAttributesModel):
    __tablename__ = "nota_fiscal"
    __table_args__ = {"schema": "hub"}

    id = Column(Integer, primary_key=True, autoincrement=True)
    nota_id = Column(BigInteger, nullable=False)
    chave_acesso = Column(String, nullable=False)
    versao = Column(String, nullable=False)
    especie = Column(String, nullable=False)
    modelo = Column(String, nullable=False)
    numero = Column(Integer, nullable=False)
    serie = Column(String, nullable=False)
    data_emissao = Column(TIMESTAMP, nullable=False)
    data_entrega = Column(Date, nullable=True)
    pedido_id = Column(Integer, index=True)
    tipo_pedido = Column(Integer)
    tipo_nota = Column(String, nullable=False)
    situacao = Column(String, nullable=False)
    emitente_cnpj = Column(String, nullable=False)
    destinatario_cnpj = Column(String, nullable=False)
    destinatario_nome = Column(String, nullable=True, comment="Nome Completo do Destinatário")
    destinatario_logradouro = Column(String, nullable=True)
    destinatario_numero = Column(String, nullable=True)
    destinatario_complemento = Column(String, nullable=True)
    destinatario_bairro = Column(String, nullable=True)
    destinatario_cidade = Column(String, nullable=True)
    destinatario_estado = Column(String, nullable=True)
    destinatario_pais = Column(String, nullable=True)
    destinatario_cep = Column(String, nullable=True)
    destinatario_referencia = Column(String, nullable=True)
    destinatario_ddd_fone = Column(String, nullable=True)
    destinatario_fone = Column(String, nullable=True)
    destinatario_email = Column(String, nullable=True)
    transportadora_cnpj = Column(String)
    transportadora_veiculo_placa = Column(String)
    transportadora_veiculo_estado = Column(String)
    transportadora_reboque_placa = Column(String)
    transportadora_reboque_estado = Column(String)
    observacao = Column(String)
    nota_fiscal_origem = Column(Integer)
    serie_origem = Column(String)
    chave_acesso_origem = Column(String)
    tipo_ambiente_nfe = Column(Integer, nullable=False)
    protocolo = Column(String, nullable=False)
    cfop = Column(Integer, nullable=False)
    quantidade = Column(Float, nullable=False)
    valor_desconto = Column(Float)
    valor_base_icms = Column(Float)
    valor_icms = Column(Float)
    valor_base_diferido = Column(Float)
    valor_base_isenta = Column(Float)
    valor_base_ipi = Column(Float)
    valor_ipi = Column(Float)
    valor_base_st = Column(Float)
    valor_icms_st = Column(Float)
    valor_total_produtos = Column(Float, nullable=False)
    peso_bruto = Column(Float)
    peso_liquido = Column(Float)
    valor_frete = Column(Float)
    valor_seguro = Column(Float)
    valor_embalagem = Column(Float)
    valor_outras_despesas = Column(Float)
    volumes_marca = Column(String)
    volumes_quantidade = Column(Integer)
    modalidade_frete = Column(Integer)
    data_cancelamento = Column(TIMESTAMP)
    valor_total_nota = Column(Float, nullable=True)
    data_autorizacao = Column(TIMESTAMP, nullable=True)
    estoque_tipo = Column(String, nullable=True)

    itens = relationship("NotaFiscalItem", back_populates="nota_fiscal")


class NotaFiscalItem(Base):
    __tablename__ = "nota_fiscal_itens"
    __table_args__ = {"schema": "hub"}

    id = Column(Integer, primary_key=True, autoincrement=True)
    notafiscal_id = Column(Integer, ForeignKey("hub.nota_fiscal.id"), nullable=False)
    sequencia = Column(Integer, nullable=False)
    produto = Column(Integer, nullable=False)
    caixa = Column(Integer)
    lote = Column(String)
    quantidade = Column(Float, nullable=False)
    cfop = Column(Integer, nullable=False)
    ncm = Column(String, nullable=False)
    valor_bruto = Column(Float, nullable=False)
    valor_desconto = Column(Float)
    valor_base_icms = Column(Float)
    valor_icms = Column(Float)
    valor_base_diferido = Column(Float)
    valor_base_isenta = Column(Float)
    valor_base_ipi = Column(Float)
    valor_ipi = Column(Float)
    valor_icms_st = Column(Float)
    valor_base_st = Column(Float)
    valor_liquido = Column(Float, nullable=False)
    valor_total_produto = Column(Float, nullable=False)
    valor_aliquota_icms = Column(Float, nullable=False)
    valor_aliquota_ipi = Column(Float, nullable=False)
    valor_aliquota_pis = Column(Float, nullable=False)
    valor_aliquota_cofins = Column(Float, nullable=False)
    data_validade = Column(Date)
    valor_despesa = Column(Float)
    valor_tributos = Column(Float)
    valor_cstb_pis = Column(String, nullable=False)
    valor_cstb_cofins = Column(String, nullable=False)
    valor_base_pis = Column(Float)
    valor_pis = Column(Float)
    valor_base_cofins = Column(Float)
    valor_cofins = Column(Float)
    valor_redutor_base_icms = Column(Float)
    sequencia_origem = Column(Integer)
    peso_bruto = Column(Float)
    peso_liquido = Column(Float)
    valor_frete = Column(Float)
    valor_seguro = Column(Float)
    valor_embalagem = Column(Float)
    valor_outras_despesas = Column(Float)
    valor_cst_ipi = Column(Float)
    valor_modbc_icms = Column(Float)
    valor_modb_cst = Column(Float)
    valor_modb_ipi = Column(Float)
    valor_icms_substituto = Column(Float)
    valor_base_cst_ret = Column(Float)
    valor_icms_ret = Column(Float)
    ean = Column(String)
    volume = Column(String)
    created_at = Column(TIMESTAMP, default=func.now(), nullable=True)
    updated_at = Column(TIMESTAMP, default=func.now(), onupdate=func.now(), nullable=True)

    nota_fiscal = relationship("NotaFiscal", back_populates="itens")
